/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiderIndexRouteImport } from './routes/rider/index'
import { Route as MerchantIndexRouteImport } from './routes/merchant/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RiderEarningsRouteImport } from './routes/rider/earnings'
import { Route as RiderDispatchRouteImport } from './routes/rider/dispatch'
import { Route as MerchantInvoicingRouteImport } from './routes/merchant/invoicing'
import { Route as MerchantBulkRouteImport } from './routes/merchant/bulk'
import { Route as MerchantApiKeysRouteImport } from './routes/merchant/api-keys'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppWalletRouteImport } from './routes/_authenticated/app.wallet'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppOrdersRouteImport } from './routes/_authenticated/app.orders'
import { Route as AuthenticatedAppBookRouteImport } from './routes/_authenticated/app.book'
import { Route as AuthenticatedAppTrackOrderIdRouteImport } from './routes/_authenticated/app.track.$orderId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RiderRoute,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RiderEarningsRoute = RiderEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => RiderRoute,
} as any)
const RiderDispatchRoute = RiderDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => RiderRoute,
} as any)
const MerchantInvoicingRoute = MerchantInvoicingRouteImport.update({
  id: '/invoicing',
  path: '/invoicing',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantBulkRoute = MerchantBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantApiKeysRoute = MerchantApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => MerchantRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWalletRoute = AuthenticatedAppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOrdersRoute = AuthenticatedAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBookRoute = AuthenticatedAppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTrackOrderIdRoute =
  AuthenticatedAppTrackOrderIdRouteImport.update({
    id: '/track/$orderId',
    path: '/track/$orderId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/rider': typeof RiderRouteWithChildren
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/merchant/api-keys': typeof MerchantApiKeysRoute
  '/merchant/bulk': typeof MerchantBulkRoute
  '/merchant/invoicing': typeof MerchantInvoicingRoute
  '/rider/dispatch': typeof RiderDispatchRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/app/book': typeof AuthenticatedAppBookRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/wallet': typeof AuthenticatedAppWalletRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/track/$orderId': typeof AuthenticatedAppTrackOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/merchant/api-keys': typeof MerchantApiKeysRoute
  '/merchant/bulk': typeof MerchantBulkRoute
  '/merchant/invoicing': typeof MerchantInvoicingRoute
  '/rider/dispatch': typeof RiderDispatchRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/admin': typeof AdminIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/rider': typeof RiderIndexRoute
  '/app/book': typeof AuthenticatedAppBookRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/wallet': typeof AuthenticatedAppWalletRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/track/$orderId': typeof AuthenticatedAppTrackOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/rider': typeof RiderRouteWithChildren
  '/signup': typeof SignupRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/merchant/api-keys': typeof MerchantApiKeysRoute
  '/merchant/bulk': typeof MerchantBulkRoute
  '/merchant/invoicing': typeof MerchantInvoicingRoute
  '/rider/dispatch': typeof RiderDispatchRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/_authenticated/app/book': typeof AuthenticatedAppBookRoute
  '/_authenticated/app/orders': typeof AuthenticatedAppOrdersRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/wallet': typeof AuthenticatedAppWalletRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/track/$orderId': typeof AuthenticatedAppTrackOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/merchant'
    | '/rider'
    | '/signup'
    | '/app'
    | '/admin/analytics'
    | '/admin/finance'
    | '/merchant/api-keys'
    | '/merchant/bulk'
    | '/merchant/invoicing'
    | '/rider/dispatch'
    | '/rider/earnings'
    | '/admin/'
    | '/merchant/'
    | '/rider/'
    | '/app/book'
    | '/app/orders'
    | '/app/profile'
    | '/app/wallet'
    | '/app/'
    | '/app/track/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/analytics'
    | '/admin/finance'
    | '/merchant/api-keys'
    | '/merchant/bulk'
    | '/merchant/invoicing'
    | '/rider/dispatch'
    | '/rider/earnings'
    | '/admin'
    | '/merchant'
    | '/rider'
    | '/app/book'
    | '/app/orders'
    | '/app/profile'
    | '/app/wallet'
    | '/app'
    | '/app/track/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/login'
    | '/merchant'
    | '/rider'
    | '/signup'
    | '/_authenticated/app'
    | '/admin/analytics'
    | '/admin/finance'
    | '/merchant/api-keys'
    | '/merchant/bulk'
    | '/merchant/invoicing'
    | '/rider/dispatch'
    | '/rider/earnings'
    | '/admin/'
    | '/merchant/'
    | '/rider/'
    | '/_authenticated/app/book'
    | '/_authenticated/app/orders'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/wallet'
    | '/_authenticated/app/'
    | '/_authenticated/app/track/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  RiderRoute: typeof RiderRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/': {
      id: '/rider/'
      path: '/'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof RiderRoute
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rider/earnings': {
      id: '/rider/earnings'
      path: '/earnings'
      fullPath: '/rider/earnings'
      preLoaderRoute: typeof RiderEarningsRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/dispatch': {
      id: '/rider/dispatch'
      path: '/dispatch'
      fullPath: '/rider/dispatch'
      preLoaderRoute: typeof RiderDispatchRouteImport
      parentRoute: typeof RiderRoute
    }
    '/merchant/invoicing': {
      id: '/merchant/invoicing'
      path: '/invoicing'
      fullPath: '/merchant/invoicing'
      preLoaderRoute: typeof MerchantInvoicingRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/bulk': {
      id: '/merchant/bulk'
      path: '/bulk'
      fullPath: '/merchant/bulk'
      preLoaderRoute: typeof MerchantBulkRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/api-keys': {
      id: '/merchant/api-keys'
      path: '/api-keys'
      fullPath: '/merchant/api-keys'
      preLoaderRoute: typeof MerchantApiKeysRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/wallet': {
      id: '/_authenticated/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AuthenticatedAppWalletRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/orders': {
      id: '/_authenticated/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AuthenticatedAppOrdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/book': {
      id: '/_authenticated/app/book'
      path: '/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AuthenticatedAppBookRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/track/$orderId': {
      id: '/_authenticated/app/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/app/track/$orderId'
      preLoaderRoute: typeof AuthenticatedAppTrackOrderIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBookRoute: typeof AuthenticatedAppBookRoute
  AuthenticatedAppOrdersRoute: typeof AuthenticatedAppOrdersRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppWalletRoute: typeof AuthenticatedAppWalletRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppTrackOrderIdRoute: typeof AuthenticatedAppTrackOrderIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBookRoute: AuthenticatedAppBookRoute,
  AuthenticatedAppOrdersRoute: AuthenticatedAppOrdersRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppWalletRoute: AuthenticatedAppWalletRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppTrackOrderIdRoute: AuthenticatedAppTrackOrderIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MerchantRouteChildren {
  MerchantApiKeysRoute: typeof MerchantApiKeysRoute
  MerchantBulkRoute: typeof MerchantBulkRoute
  MerchantInvoicingRoute: typeof MerchantInvoicingRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantApiKeysRoute: MerchantApiKeysRoute,
  MerchantBulkRoute: MerchantBulkRoute,
  MerchantInvoicingRoute: MerchantInvoicingRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

interface RiderRouteChildren {
  RiderDispatchRoute: typeof RiderDispatchRoute
  RiderEarningsRoute: typeof RiderEarningsRoute
  RiderIndexRoute: typeof RiderIndexRoute
}

const RiderRouteChildren: RiderRouteChildren = {
  RiderDispatchRoute: RiderDispatchRoute,
  RiderEarningsRoute: RiderEarningsRoute,
  RiderIndexRoute: RiderIndexRoute,
}

const RiderRouteWithChildren = RiderRoute._addFileChildren(RiderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MerchantRoute: MerchantRouteWithChildren,
  RiderRoute: RiderRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
