/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RiderSignupRouteImport } from './routes/rider-signup'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DispatcherRouteImport } from './routes/dispatcher'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as RiderIndexRouteImport } from './routes/rider/index'
import { Route as MerchantIndexRouteImport } from './routes/merchant/index'
import { Route as DispatcherIndexRouteImport } from './routes/dispatcher/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RiderProfileRouteImport } from './routes/rider/profile'
import { Route as RiderEarningsRouteImport } from './routes/rider/earnings'
import { Route as RiderDocumentsRouteImport } from './routes/rider/documents'
import { Route as RiderDispatchRouteImport } from './routes/rider/dispatch'
import { Route as MerchantInvoicingRouteImport } from './routes/merchant/invoicing'
import { Route as MerchantBulkRouteImport } from './routes/merchant/bulk'
import { Route as MerchantApiKeysRouteImport } from './routes/merchant/api-keys'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminDriversRouteImport } from './routes/admin/drivers'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppWalletRouteImport } from './routes/_authenticated/app.wallet'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppOrdersRouteImport } from './routes/_authenticated/app.orders'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/app.chat'
import { Route as AuthenticatedAppBookRouteImport } from './routes/_authenticated/app.book'
import { Route as AuthenticatedAppTrackOrderIdRouteImport } from './routes/_authenticated/app.track.$orderId'
import { Route as AuthenticatedAppChatCidRouteImport } from './routes/_authenticated/app.chat.$cid'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderSignupRoute = RiderSignupRouteImport.update({
  id: '/rider-signup',
  path: '/rider-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatcherRoute = DispatcherRouteImport.update({
  id: '/dispatcher',
  path: '/dispatcher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRoute,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RiderRoute,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const DispatcherIndexRoute = DispatcherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DispatcherRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RiderProfileRoute = RiderProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RiderRoute,
} as any)
const RiderEarningsRoute = RiderEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => RiderRoute,
} as any)
const RiderDocumentsRoute = RiderDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => RiderRoute,
} as any)
const RiderDispatchRoute = RiderDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => RiderRoute,
} as any)
const MerchantInvoicingRoute = MerchantInvoicingRouteImport.update({
  id: '/invoicing',
  path: '/invoicing',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantBulkRoute = MerchantBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantApiKeysRoute = MerchantApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => MerchantRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWalletRoute = AuthenticatedAppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOrdersRoute = AuthenticatedAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBookRoute = AuthenticatedAppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTrackOrderIdRoute =
  AuthenticatedAppTrackOrderIdRouteImport.update({
    id: '/track/$orderId',
    path: '/track/$orderId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatCidRoute = AuthenticatedAppChatCidRouteImport.update({
  id: '/$cid',
  path: '/$cid',
  getParentRoute: () => AuthenticatedAppChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dispatcher': typeof DispatcherRouteWithChildren
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/rider': typeof RiderRouteWithChildren
  '/rider-signup': typeof RiderSignupRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/users': typeof AdminUsersRoute
  '/merchant/api-keys': typeof MerchantApiKeysRoute
  '/merchant/bulk': typeof MerchantBulkRoute
  '/merchant/invoicing': typeof MerchantInvoicingRoute
  '/rider/dispatch': typeof RiderDispatchRoute
  '/rider/documents': typeof RiderDocumentsRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/profile': typeof RiderProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/dispatcher/': typeof DispatcherIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/support/': typeof SupportIndexRoute
  '/app/book': typeof AuthenticatedAppBookRoute
  '/app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/wallet': typeof AuthenticatedAppWalletRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/chat/$cid': typeof AuthenticatedAppChatCidRoute
  '/app/track/$orderId': typeof AuthenticatedAppTrackOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rider-signup': typeof RiderSignupRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/users': typeof AdminUsersRoute
  '/merchant/api-keys': typeof MerchantApiKeysRoute
  '/merchant/bulk': typeof MerchantBulkRoute
  '/merchant/invoicing': typeof MerchantInvoicingRoute
  '/rider/dispatch': typeof RiderDispatchRoute
  '/rider/documents': typeof RiderDocumentsRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/profile': typeof RiderProfileRoute
  '/admin': typeof AdminIndexRoute
  '/dispatcher': typeof DispatcherIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/rider': typeof RiderIndexRoute
  '/support': typeof SupportIndexRoute
  '/app/book': typeof AuthenticatedAppBookRoute
  '/app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/wallet': typeof AuthenticatedAppWalletRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/chat/$cid': typeof AuthenticatedAppChatCidRoute
  '/app/track/$orderId': typeof AuthenticatedAppTrackOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dispatcher': typeof DispatcherRouteWithChildren
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/rider': typeof RiderRouteWithChildren
  '/rider-signup': typeof RiderSignupRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/users': typeof AdminUsersRoute
  '/merchant/api-keys': typeof MerchantApiKeysRoute
  '/merchant/bulk': typeof MerchantBulkRoute
  '/merchant/invoicing': typeof MerchantInvoicingRoute
  '/rider/dispatch': typeof RiderDispatchRoute
  '/rider/documents': typeof RiderDocumentsRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/profile': typeof RiderProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/dispatcher/': typeof DispatcherIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/support/': typeof SupportIndexRoute
  '/_authenticated/app/book': typeof AuthenticatedAppBookRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/orders': typeof AuthenticatedAppOrdersRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/wallet': typeof AuthenticatedAppWalletRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/chat/$cid': typeof AuthenticatedAppChatCidRoute
  '/_authenticated/app/track/$orderId': typeof AuthenticatedAppTrackOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dispatcher'
    | '/login'
    | '/merchant'
    | '/rider'
    | '/rider-signup'
    | '/signup'
    | '/support'
    | '/app'
    | '/admin/analytics'
    | '/admin/drivers'
    | '/admin/finance'
    | '/admin/users'
    | '/merchant/api-keys'
    | '/merchant/bulk'
    | '/merchant/invoicing'
    | '/rider/dispatch'
    | '/rider/documents'
    | '/rider/earnings'
    | '/rider/profile'
    | '/admin/'
    | '/dispatcher/'
    | '/merchant/'
    | '/rider/'
    | '/support/'
    | '/app/book'
    | '/app/chat'
    | '/app/notifications'
    | '/app/orders'
    | '/app/profile'
    | '/app/wallet'
    | '/app/'
    | '/app/chat/$cid'
    | '/app/track/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/rider-signup'
    | '/signup'
    | '/admin/analytics'
    | '/admin/drivers'
    | '/admin/finance'
    | '/admin/users'
    | '/merchant/api-keys'
    | '/merchant/bulk'
    | '/merchant/invoicing'
    | '/rider/dispatch'
    | '/rider/documents'
    | '/rider/earnings'
    | '/rider/profile'
    | '/admin'
    | '/dispatcher'
    | '/merchant'
    | '/rider'
    | '/support'
    | '/app/book'
    | '/app/chat'
    | '/app/notifications'
    | '/app/orders'
    | '/app/profile'
    | '/app/wallet'
    | '/app'
    | '/app/chat/$cid'
    | '/app/track/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/dispatcher'
    | '/login'
    | '/merchant'
    | '/rider'
    | '/rider-signup'
    | '/signup'
    | '/support'
    | '/_authenticated/app'
    | '/admin/analytics'
    | '/admin/drivers'
    | '/admin/finance'
    | '/admin/users'
    | '/merchant/api-keys'
    | '/merchant/bulk'
    | '/merchant/invoicing'
    | '/rider/dispatch'
    | '/rider/documents'
    | '/rider/earnings'
    | '/rider/profile'
    | '/admin/'
    | '/dispatcher/'
    | '/merchant/'
    | '/rider/'
    | '/support/'
    | '/_authenticated/app/book'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/orders'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/wallet'
    | '/_authenticated/app/'
    | '/_authenticated/app/chat/$cid'
    | '/_authenticated/app/track/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DispatcherRoute: typeof DispatcherRouteWithChildren
  LoginRoute: typeof LoginRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  RiderRoute: typeof RiderRouteWithChildren
  RiderSignupRoute: typeof RiderSignupRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider-signup': {
      id: '/rider-signup'
      path: '/rider-signup'
      fullPath: '/rider-signup'
      preLoaderRoute: typeof RiderSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatcher': {
      id: '/dispatcher'
      path: '/dispatcher'
      fullPath: '/dispatcher'
      preLoaderRoute: typeof DispatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/rider/': {
      id: '/rider/'
      path: '/'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof RiderRoute
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/dispatcher/': {
      id: '/dispatcher/'
      path: '/'
      fullPath: '/dispatcher/'
      preLoaderRoute: typeof DispatcherIndexRouteImport
      parentRoute: typeof DispatcherRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rider/profile': {
      id: '/rider/profile'
      path: '/profile'
      fullPath: '/rider/profile'
      preLoaderRoute: typeof RiderProfileRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/earnings': {
      id: '/rider/earnings'
      path: '/earnings'
      fullPath: '/rider/earnings'
      preLoaderRoute: typeof RiderEarningsRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/documents': {
      id: '/rider/documents'
      path: '/documents'
      fullPath: '/rider/documents'
      preLoaderRoute: typeof RiderDocumentsRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/dispatch': {
      id: '/rider/dispatch'
      path: '/dispatch'
      fullPath: '/rider/dispatch'
      preLoaderRoute: typeof RiderDispatchRouteImport
      parentRoute: typeof RiderRoute
    }
    '/merchant/invoicing': {
      id: '/merchant/invoicing'
      path: '/invoicing'
      fullPath: '/merchant/invoicing'
      preLoaderRoute: typeof MerchantInvoicingRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/bulk': {
      id: '/merchant/bulk'
      path: '/bulk'
      fullPath: '/merchant/bulk'
      preLoaderRoute: typeof MerchantBulkRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/api-keys': {
      id: '/merchant/api-keys'
      path: '/api-keys'
      fullPath: '/merchant/api-keys'
      preLoaderRoute: typeof MerchantApiKeysRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/wallet': {
      id: '/_authenticated/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AuthenticatedAppWalletRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/orders': {
      id: '/_authenticated/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AuthenticatedAppOrdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/book': {
      id: '/_authenticated/app/book'
      path: '/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AuthenticatedAppBookRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/track/$orderId': {
      id: '/_authenticated/app/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/app/track/$orderId'
      preLoaderRoute: typeof AuthenticatedAppTrackOrderIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat/$cid': {
      id: '/_authenticated/app/chat/$cid'
      path: '/$cid'
      fullPath: '/app/chat/$cid'
      preLoaderRoute: typeof AuthenticatedAppChatCidRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
  }
}

interface AuthenticatedAppChatRouteChildren {
  AuthenticatedAppChatCidRoute: typeof AuthenticatedAppChatCidRoute
}

const AuthenticatedAppChatRouteChildren: AuthenticatedAppChatRouteChildren = {
  AuthenticatedAppChatCidRoute: AuthenticatedAppChatCidRoute,
}

const AuthenticatedAppChatRouteWithChildren =
  AuthenticatedAppChatRoute._addFileChildren(AuthenticatedAppChatRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBookRoute: typeof AuthenticatedAppBookRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRouteWithChildren
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppOrdersRoute: typeof AuthenticatedAppOrdersRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppWalletRoute: typeof AuthenticatedAppWalletRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppTrackOrderIdRoute: typeof AuthenticatedAppTrackOrderIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBookRoute: AuthenticatedAppBookRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRouteWithChildren,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppOrdersRoute: AuthenticatedAppOrdersRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppWalletRoute: AuthenticatedAppWalletRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppTrackOrderIdRoute: AuthenticatedAppTrackOrderIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DispatcherRouteChildren {
  DispatcherIndexRoute: typeof DispatcherIndexRoute
}

const DispatcherRouteChildren: DispatcherRouteChildren = {
  DispatcherIndexRoute: DispatcherIndexRoute,
}

const DispatcherRouteWithChildren = DispatcherRoute._addFileChildren(
  DispatcherRouteChildren,
)

interface MerchantRouteChildren {
  MerchantApiKeysRoute: typeof MerchantApiKeysRoute
  MerchantBulkRoute: typeof MerchantBulkRoute
  MerchantInvoicingRoute: typeof MerchantInvoicingRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantApiKeysRoute: MerchantApiKeysRoute,
  MerchantBulkRoute: MerchantBulkRoute,
  MerchantInvoicingRoute: MerchantInvoicingRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

interface RiderRouteChildren {
  RiderDispatchRoute: typeof RiderDispatchRoute
  RiderDocumentsRoute: typeof RiderDocumentsRoute
  RiderEarningsRoute: typeof RiderEarningsRoute
  RiderProfileRoute: typeof RiderProfileRoute
  RiderIndexRoute: typeof RiderIndexRoute
}

const RiderRouteChildren: RiderRouteChildren = {
  RiderDispatchRoute: RiderDispatchRoute,
  RiderDocumentsRoute: RiderDocumentsRoute,
  RiderEarningsRoute: RiderEarningsRoute,
  RiderProfileRoute: RiderProfileRoute,
  RiderIndexRoute: RiderIndexRoute,
}

const RiderRouteWithChildren = RiderRoute._addFileChildren(RiderRouteChildren)

interface SupportRouteChildren {
  SupportIndexRoute: typeof SupportIndexRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportIndexRoute: SupportIndexRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DispatcherRoute: DispatcherRouteWithChildren,
  LoginRoute: LoginRoute,
  MerchantRoute: MerchantRouteWithChildren,
  RiderRoute: RiderRouteWithChildren,
  RiderSignupRoute: RiderSignupRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
