// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// @supabase/realtime-js's RealtimeClient constructor — which runs eagerly as
// part of createClient(), with no .channel()/.subscribe() call needed at all
// — synchronously calls WebSocketFactory.getWebSocketConstructor(). On
// Node.js <22 (no native global WebSocket) with no `transport` override, that
// throws immediately, crashing SSR for every route that touches `supabase`
// (i.e. every authenticated route, since _authenticated.tsx's beforeLoad
// calls supabase.auth.getSession()). `import.meta.env.SSR` is statically
// replaced by Vite at build time, so this whole branch — including the `ws`
// import — is dead-code-eliminated from the browser bundle; browsers already
// have native WebSocket and never need it.
const realtimeTransport =
  import.meta.env.SSR && typeof globalThis.WebSocket === "undefined"
    ? (await import("ws")).default
    : undefined;

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    // Log internally but never expose env var names or URLs to the UI
    console.error("[Rapide] Backend configuration missing. Check environment variables.");
    throw new Error("Service configuration error. Please contact support.");
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    ...(realtimeTransport ? { realtime: { transport: realtimeTransport as never } } : {}),
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
